# Generated by Django 6.0 on 2025-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text="The user's question.")),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('answer_text', models.TextField(blank=True, help_text="The Imam's answer.", null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.CharField(blank=True, help_text='Name of the person attempting to answer', max_length=100)),
            ],
            options={
                'ordering': ['-asked_at'],
            },
        ),
    ]
