# Generated by Django 6.0 on 2025-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text="If unchecked, this won't show in the app.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', models.DateField(help_text='Date this content should be displayed.', unique=True)),
                ('content_type', models.CharField(choices=[('VERSE', 'Quran Verse'), ('HADITH', 'Hadith'), ('QUOTE', 'Islamic Quote')], default='VERSE', max_length=10)),
                ('title', models.CharField(help_text="e.g., 'Verse of the Day'", max_length=200)),
                ('arabic_text', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(help_text='English translation or main content.')),
                ('reference', models.CharField(blank=True, help_text="e.g., 'Sahih Bukhari 1:1' or 'Surah Al-Fatiha'", max_length=100)),
            ],
            options={
                'ordering': ['-date_for'],
            },
        ),
    ]
