# Generated by Django 6.0 on 2025-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Goal amount (e.g., 5000.00)', max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount collected so far', max_digits=12)),
                ('bank_details', models.TextField(help_text='Instructions for payment (Bank Name, Account No, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
